### PR TITLE
Update attendance

### PR DESCRIPTION
**Pull request by ArPau**
Really liked the name bonerAttendance!

Made two changes:
Changed attendance to be bonerAttendance and removed bonerAttendance, also removed managing and viewing of bonerAttendance
Removed 'Nummer' line at 50% on the stats page

### CODE REVIEW

**Comment by CodeyBoi** [comment]
`showBoner` must be removed from `src/app/stats/page.tsx` as well. Otherwise it Looks Good To Me (LGTM)!

**Comment by CodeyBoi** [comment]
Also, you must add your name to the list in `src/app/about/page.tsx`

**Comment by CodeyBoi** [comment]
There are some unused imports and variables, e.g. in `stats/layout.tsx` Run `yarn run format && yarn run lint` to get rid of them

**Comment by ArPau** [comment]
Running `yarn run format && yarn run lint` changed files not touched by previous commits but will add them as well here

**Review by CodeyBoi — CHANGES_REQUESTED** [review]
`bun lint` is complaining about an unused variable `lastAttendance`, used for calculating where the "Nummer" symbol should be placed. Remove this and I think we're done.

**Comment by ArPau** [comment]
Damn, one really needs to be careful when editing. It's really easy to miss small things.

**Review by CodeyBoi — APPROVED** [review]
LGTM!

**Pull request merged**
